[package]
name = "linked_list_rs"
version = "0.1.0"
authors = ["Mibblez <abeninati01@manhattan.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
